// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banner.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBanner = `-- name: CreateBanner :one
INSERT INTO banners (title, subtitle, button_text, button_url, image_url, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, subtitle, button_text, button_url, image_url, is_active, sort_order, created_at, updated_at
`

type CreateBannerParams struct {
	Title      pgtype.Text `json:"title"`
	Subtitle   pgtype.Text `json:"subtitle"`
	ButtonText pgtype.Text `json:"button_text"`
	ButtonUrl  pgtype.Text `json:"button_url"`
	ImageUrl   string      `json:"image_url"`
	IsActive   bool        `json:"is_active"`
	SortOrder  int32       `json:"sort_order"`
}

func (q *Queries) CreateBanner(ctx context.Context, arg CreateBannerParams) (Banner, error) {
	row := q.db.QueryRow(ctx, createBanner,
		arg.Title,
		arg.Subtitle,
		arg.ButtonText,
		arg.ButtonUrl,
		arg.ImageUrl,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Banner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.ButtonText,
		&i.ButtonUrl,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBanner = `-- name: DeleteBanner :exec
DELETE FROM banners
WHERE id = $1
`

func (q *Queries) DeleteBanner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBanner, id)
	return err
}

const getActiveBanners = `-- name: GetActiveBanners :many
SELECT id, title, subtitle, button_text, button_url, image_url, is_active, sort_order, created_at, updated_at FROM banners
WHERE is_active = true
ORDER BY sort_order ASC
`

func (q *Queries) GetActiveBanners(ctx context.Context) ([]Banner, error) {
	rows, err := q.db.Query(ctx, getActiveBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Banner{}
	for rows.Next() {
		var i Banner
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.ButtonText,
			&i.ButtonUrl,
			&i.ImageUrl,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBanner = `-- name: UpdateBanner :one
UPDATE banners
SET title = $2, subtitle = $3, button_text = $4, button_url = $5, image_url = $6, is_active = $7, sort_order = $8, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, subtitle, button_text, button_url, image_url, is_active, sort_order, created_at, updated_at
`

type UpdateBannerParams struct {
	ID         uuid.UUID   `json:"id"`
	Title      pgtype.Text `json:"title"`
	Subtitle   pgtype.Text `json:"subtitle"`
	ButtonText pgtype.Text `json:"button_text"`
	ButtonUrl  pgtype.Text `json:"button_url"`
	ImageUrl   string      `json:"image_url"`
	IsActive   bool        `json:"is_active"`
	SortOrder  int32       `json:"sort_order"`
}

func (q *Queries) UpdateBanner(ctx context.Context, arg UpdateBannerParams) (Banner, error) {
	row := q.db.QueryRow(ctx, updateBanner,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.ButtonText,
		arg.ButtonUrl,
		arg.ImageUrl,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Banner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.ButtonText,
		&i.ButtonUrl,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
