// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `-- name: AddToCart :one
INSERT INTO cart_items (user_id, variant_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, variant_id) DO UPDATE
SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, variant_id, quantity, created_at, updated_at
`

type AddToCartParams struct {
	UserID    uuid.UUID `json:"user_id"`
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addToCart, arg.UserID, arg.VariantID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const getCart = `-- name: GetCart :many
SELECT
    ci.id,
    ci.quantity,
    ci.variant_id,

    pv.label,
    pv.color,
    pv.stock,

    p.id AS product_id,
    p.name AS product_name,
    p.price,
    p.discount,

    -- قیمت نهایی بعد از تخفیف
    ROUND(p.price * (1 - COALESCE(p.discount, 0) / 100)) AS final_price,

    pi.url AS image_url

FROM cart_items ci

JOIN product_variants pv
    ON pv.id = ci.variant_id

JOIN products p
    ON p.id = pv.product_id

LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE product_id = p.id
    ORDER BY created_at
    LIMIT 1
) pi ON true

WHERE ci.user_id = $1

ORDER BY ci.created_at DESC
`

type GetCartRow struct {
	ID          uuid.UUID      `json:"id"`
	Quantity    int32          `json:"quantity"`
	VariantID   uuid.UUID      `json:"variant_id"`
	Label       string         `json:"label"`
	Color       pgtype.Text    `json:"color"`
	Stock       int32          `json:"stock"`
	ProductID   uuid.UUID      `json:"product_id"`
	ProductName string         `json:"product_name"`
	Price       pgtype.Numeric `json:"price"`
	Discount    pgtype.Numeric `json:"discount"`
	FinalPrice  float64        `json:"final_price"`
	ImageUrl    string         `json:"image_url"`
}

func (q *Queries) GetCart(ctx context.Context, userID uuid.UUID) ([]GetCartRow, error) {
	rows, err := q.db.Query(ctx, getCart, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartRow{}
	for rows.Next() {
		var i GetCartRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.VariantID,
			&i.Label,
			&i.Color,
			&i.Stock,
			&i.ProductID,
			&i.ProductName,
			&i.Price,
			&i.Discount,
			&i.FinalPrice,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromCart = `-- name: RemoveFromCart :exec
DELETE FROM cart_items
WHERE id = $1
  AND user_id = $2
`

type RemoveFromCartParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error {
	_, err := q.db.Exec(ctx, removeFromCart, arg.ID, arg.UserID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET
    quantity = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
  AND user_id = $3
RETURNING id, user_id, variant_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	Quantity int32     `json:"quantity"`
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.Quantity, arg.ID, arg.UserID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
