// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id, image_url)
VALUES ($1, $2, $3)
RETURNING id, name, parent_id, created_at, updated_at, image_url
`

type CreateCategoryParams struct {
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
	ImageUrl pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.ParentID, arg.ImageUrl)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, parent_id, image_url, created_at, updated_at FROM categories
ORDER BY name
`

type GetAllCategoriesRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	ParentID  pgtype.UUID      `json:"parent_id"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllCategories(ctx context.Context) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCategoriesRow{}
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, parent_id, image_url, created_at, updated_at FROM categories
WHERE id = $1
`

type GetCategoryByIDRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	ParentID  pgtype.UUID      `json:"parent_id"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
