// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT
    p.id,
    p.name,
    COALESCE(SUM(pv.stock), 0)::bigint AS stock
FROM products p
LEFT JOIN product_variants pv
    ON pv.product_id = p.id
WHERE p.is_active = TRUE
GROUP BY p.id, p.name
HAVING COALESCE(SUM(pv.stock), 0) <= 5
ORDER BY stock ASC, p.name ASC
LIMIT 10
`

type GetLowStockProductsRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Stock int64     `json:"stock"`
}

func (q *Queries) GetLowStockProducts(ctx context.Context) ([]GetLowStockProductsRow, error) {
	rows, err := q.db.Query(ctx, getLowStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLowStockProductsRow{}
	for rows.Next() {
		var i GetLowStockProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Stock); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaidOrdersCount = `-- name: GetPaidOrdersCount :one
SELECT COUNT(*)
FROM orders
WHERE status = 'paid'
`

func (q *Queries) GetPaidOrdersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getPaidOrdersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingOrdersCount = `-- name: GetPendingOrdersCount :one
SELECT COUNT(*)
FROM orders
WHERE status = 'pending'
`

func (q *Queries) GetPendingOrdersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getPendingOrdersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentOrders = `-- name: GetRecentOrders :many
SELECT
    o.id,
    o.user_id,
    u.full_name AS customer_name,
    o.total_price,
    o.status,
    o.created_at
FROM orders o
JOIN users u ON u.id = o.user_id
ORDER BY o.created_at DESC
LIMIT 10
`

type GetRecentOrdersRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	CustomerName string             `json:"customer_name"`
	TotalPrice   int64              `json:"total_price"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentOrders(ctx context.Context) ([]GetRecentOrdersRow, error) {
	rows, err := q.db.Query(ctx, getRecentOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentOrdersRow{}
	for rows.Next() {
		var i GetRecentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesLast7Days = `-- name: GetSalesLast7Days :many
SELECT
    d::date AS date,
    COALESCE(SUM(o.total_price), 0)::bigint AS amount
FROM generate_series(
    CURRENT_DATE - INTERVAL '6 days',
    CURRENT_DATE,
    INTERVAL '1 day'
) AS d
LEFT JOIN orders o
    ON o.created_at::date = d::date
    AND o.status IN ('paid', 'shipped', 'delivered')
GROUP BY d::date
ORDER BY d::date
`

type GetSalesLast7DaysRow struct {
	Date   pgtype.Date `json:"date"`
	Amount int64       `json:"amount"`
}

func (q *Queries) GetSalesLast7Days(ctx context.Context) ([]GetSalesLast7DaysRow, error) {
	rows, err := q.db.Query(ctx, getSalesLast7Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSalesLast7DaysRow{}
	for rows.Next() {
		var i GetSalesLast7DaysRow
		if err := rows.Scan(&i.Date, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayOrdersCount = `-- name: GetTodayOrdersCount :one
SELECT COUNT(*)
FROM orders
WHERE created_at >= CURRENT_DATE
`

func (q *Queries) GetTodayOrdersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTodayOrdersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTodaySales = `-- name: GetTodaySales :one
SELECT COALESCE(SUM(total_price), 0)
FROM orders
WHERE status IN ('paid', 'shipped', 'delivered')
  AND created_at >= CURRENT_DATE
`

func (q *Queries) GetTodaySales(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTodaySales)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getTopProducts = `-- name: GetTopProducts :many
SELECT
    p.id,
    p.name,
    COALESCE(SUM(oi.quantity), 0)::bigint AS sold
FROM order_items oi
JOIN orders o
    ON o.id = oi.order_id
JOIN products p
    ON p.id = oi.product_id
WHERE o.status IN ('paid', 'shipped', 'delivered')
GROUP BY p.id, p.name
ORDER BY sold DESC
LIMIT 10
`

type GetTopProductsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Sold int64     `json:"sold"`
}

func (q *Queries) GetTopProducts(ctx context.Context) ([]GetTopProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopProductsRow{}
	for rows.Next() {
		var i GetTopProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Sold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
