// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discount_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscountCode = `-- name: CreateDiscountCode :one
INSERT INTO discount_codes (
    code,
    discount_type,
    discount_value,
    min_order_amount,
    max_discount_amount,
    usage_limit,
    starts_at,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    code,
    discount_type,
    discount_value,
    min_order_amount,
    max_discount_amount,
    usage_limit,
    used_count,
    starts_at,
    expires_at,
    is_active,
    created_at,
    updated_at
`

type CreateDiscountCodeParams struct {
	Code              string             `json:"code"`
	DiscountType      string             `json:"discount_type"`
	DiscountValue     int64              `json:"discount_value"`
	MinOrderAmount    int64              `json:"min_order_amount"`
	MaxDiscountAmount pgtype.Int8        `json:"max_discount_amount"`
	UsageLimit        pgtype.Int4        `json:"usage_limit"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDiscountCode(ctx context.Context, arg CreateDiscountCodeParams) (DiscountCode, error) {
	row := q.db.QueryRow(ctx, createDiscountCode,
		arg.Code,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MinOrderAmount,
		arg.MaxDiscountAmount,
		arg.UsageLimit,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderAmount,
		&i.MaxDiscountAmount,
		&i.UsageLimit,
		&i.UsedCount,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDiscountCode = `-- name: DeleteDiscountCode :exec
DELETE FROM discount_codes
WHERE id = $1
  AND used_count = 0
`

func (q *Queries) DeleteDiscountCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiscountCode, id)
	return err
}

const getValidDiscountCode = `-- name: GetValidDiscountCode :one
SELECT
    id,
    code,
    discount_type,
    discount_value,
    min_order_amount,
    max_discount_amount,
    usage_limit,
    used_count,
    starts_at,
    expires_at,
    is_active,
    created_at,
    updated_at
FROM discount_codes
WHERE code = $1
  AND is_active = TRUE
  AND (starts_at IS NULL OR starts_at <= CURRENT_TIMESTAMP)
  AND (expires_at IS NULL OR expires_at >= CURRENT_TIMESTAMP)
  AND (usage_limit IS NULL OR used_count < usage_limit)
LIMIT 1
`

func (q *Queries) GetValidDiscountCode(ctx context.Context, code string) (DiscountCode, error) {
	row := q.db.QueryRow(ctx, getValidDiscountCode, code)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderAmount,
		&i.MaxDiscountAmount,
		&i.UsageLimit,
		&i.UsedCount,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDiscountCodeUsage = `-- name: IncrementDiscountCodeUsage :exec
UPDATE discount_codes
SET
    used_count = used_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND is_active = TRUE
  AND (usage_limit IS NULL OR used_count < usage_limit)
`

func (q *Queries) IncrementDiscountCodeUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementDiscountCodeUsage, id)
	return err
}

const listDiscountCodes = `-- name: ListDiscountCodes :many
SELECT
    id,
    code,
    discount_type,
    discount_value,
    min_order_amount,
    max_discount_amount,
    usage_limit,
    used_count,
    starts_at,
    expires_at,
    is_active,
    created_at,
    updated_at
FROM discount_codes
ORDER BY created_at DESC
`

func (q *Queries) ListDiscountCodes(ctx context.Context) ([]DiscountCode, error) {
	rows, err := q.db.Query(ctx, listDiscountCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscountCode{}
	for rows.Next() {
		var i DiscountCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinOrderAmount,
			&i.MaxDiscountAmount,
			&i.UsageLimit,
			&i.UsedCount,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
