// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CartItem struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	VariantID uuid.UUID        `json:"variant_id"`
	Quantity  int32            `json:"quantity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	ParentID  pgtype.UUID      `json:"parent_id"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Status            string             `json:"status"`
	ShippingCost      int64              `json:"shipping_cost"`
	TotalPrice        int64              `json:"total_price"`
	AddressTitle      pgtype.Text        `json:"address_title"`
	AddressProvince   pgtype.Text        `json:"address_province"`
	AddressCity       pgtype.Text        `json:"address_city"`
	AddressDetail     pgtype.Text        `json:"address_detail"`
	AddressPostalCode pgtype.Text        `json:"address_postal_code"`
	AddressLat        pgtype.Numeric     `json:"address_lat"`
	AddressLng        pgtype.Numeric     `json:"address_lng"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID         uuid.UUID   `json:"id"`
	OrderID    uuid.UUID   `json:"order_id"`
	VariantID  pgtype.UUID `json:"variant_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   int32       `json:"quantity"`
	UnitPrice  int64       `json:"unit_price"`
	TotalPrice int64       `json:"total_price"`
}

type Product struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
	Discount    pgtype.Numeric   `json:"discount"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProductImage struct {
	ID        uuid.UUID        `json:"id"`
	ProductID uuid.UUID        `json:"product_id"`
	Url       string           `json:"url"`
	IsPrimary bool             `json:"is_primary"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ProductVariant struct {
	ID        uuid.UUID        `json:"id"`
	ProductID uuid.UUID        `json:"product_id"`
	Label     string           `json:"label"`
	Color     pgtype.Text      `json:"color"`
	Stock     int32            `json:"stock"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ID        int64              `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Rating    pgtype.Int2        `json:"rating"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID        `json:"id"`
	Phone        string           `json:"phone"`
	RefreshToken string           `json:"refresh_token"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	ClientIp     *netip.Addr      `json:"client_ip"`
	IsBlocked    bool             `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type ShippingSetting struct {
	ID   int32 `json:"id"`
	Cost int64 `json:"cost"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	FullName  string           `json:"full_name"`
	Phone     string           `json:"phone"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserAddress struct {
	ID         uuid.UUID        `json:"id"`
	UserID     uuid.UUID        `json:"user_id"`
	Title      pgtype.Text      `json:"title"`
	Province   pgtype.Text      `json:"province"`
	City       pgtype.Text      `json:"city"`
	Address    pgtype.Text      `json:"address"`
	PostalCode pgtype.Text      `json:"postal_code"`
	Lat        pgtype.Numeric   `json:"lat"`
	Lng        pgtype.Numeric   `json:"lng"`
	IsDefault  bool             `json:"is_default"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Wishlist struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ProductID uuid.UUID          `json:"product_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
