// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    status,
    shipping_cost,
    total_price,
    address_title,
    address_province,
    address_city,
    address_detail,
    address_postal_code,
    address_lat,
    address_lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, status, shipping_cost, total_price, address_title, address_province, address_city, address_detail, address_postal_code, address_lat, address_lng, created_at, updated_at
`

type CreateOrderParams struct {
	UserID            uuid.UUID      `json:"user_id"`
	Status            string         `json:"status"`
	ShippingCost      int64          `json:"shipping_cost"`
	TotalPrice        int64          `json:"total_price"`
	AddressTitle      pgtype.Text    `json:"address_title"`
	AddressProvince   pgtype.Text    `json:"address_province"`
	AddressCity       pgtype.Text    `json:"address_city"`
	AddressDetail     pgtype.Text    `json:"address_detail"`
	AddressPostalCode pgtype.Text    `json:"address_postal_code"`
	AddressLat        pgtype.Numeric `json:"address_lat"`
	AddressLng        pgtype.Numeric `json:"address_lng"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.ShippingCost,
		arg.TotalPrice,
		arg.AddressTitle,
		arg.AddressProvince,
		arg.AddressCity,
		arg.AddressDetail,
		arg.AddressPostalCode,
		arg.AddressLat,
		arg.AddressLng,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ShippingCost,
		&i.TotalPrice,
		&i.AddressTitle,
		&i.AddressProvince,
		&i.AddressCity,
		&i.AddressDetail,
		&i.AddressPostalCode,
		&i.AddressLat,
		&i.AddressLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    variant_id,
    product_id,
    quantity,
    unit_price,
    total_price
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, order_id, variant_id, product_id, quantity, unit_price, total_price
`

type CreateOrderItemParams struct {
	OrderID    uuid.UUID   `json:"order_id"`
	VariantID  pgtype.UUID `json:"variant_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   int32       `json:"quantity"`
	UnitPrice  int64       `json:"unit_price"`
	TotalPrice int64       `json:"total_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    o.id, o.user_id, o.status, o.shipping_cost, o.total_price, o.address_title, o.address_province, o.address_city, o.address_detail, o.address_postal_code, o.address_lat, o.address_lng, o.created_at, o.updated_at,
    u.phone AS user_phone
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.id = $1
LIMIT 1
`

type GetOrderByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Status            string             `json:"status"`
	ShippingCost      int64              `json:"shipping_cost"`
	TotalPrice        int64              `json:"total_price"`
	AddressTitle      pgtype.Text        `json:"address_title"`
	AddressProvince   pgtype.Text        `json:"address_province"`
	AddressCity       pgtype.Text        `json:"address_city"`
	AddressDetail     pgtype.Text        `json:"address_detail"`
	AddressPostalCode pgtype.Text        `json:"address_postal_code"`
	AddressLat        pgtype.Numeric     `json:"address_lat"`
	AddressLng        pgtype.Numeric     `json:"address_lng"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UserPhone         string             `json:"user_phone"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ShippingCost,
		&i.TotalPrice,
		&i.AddressTitle,
		&i.AddressProvince,
		&i.AddressCity,
		&i.AddressDetail,
		&i.AddressPostalCode,
		&i.AddressLat,
		&i.AddressLng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserPhone,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT
    oi.id,
    oi.order_id,
    oi.variant_id,
    oi.product_id,
    oi.quantity,
    oi.unit_price,
    oi.total_price,
    p.name AS product_name,
    pv.label,
    pv.color,
    pi.url AS image_url
FROM order_items oi
JOIN products p ON p.id = oi.product_id
JOIN product_variants pv ON pv.id = oi.variant_id
LEFT JOIN LATERAL (
    SELECT url FROM product_images
    WHERE product_id = p.id
    ORDER BY created_at
    LIMIT 1
) pi ON true
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID          uuid.UUID   `json:"id"`
	OrderID     uuid.UUID   `json:"order_id"`
	VariantID   pgtype.UUID `json:"variant_id"`
	ProductID   pgtype.UUID `json:"product_id"`
	Quantity    int32       `json:"quantity"`
	UnitPrice   int64       `json:"unit_price"`
	TotalPrice  int64       `json:"total_price"`
	ProductName string      `json:"product_name"`
	Label       string      `json:"label"`
	Color       pgtype.Text `json:"color"`
	ImageUrl    string      `json:"image_url"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsRow{}
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.ProductName,
			&i.Label,
			&i.Color,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUser = `-- name: GetOrdersByUser :many
SELECT id, user_id, status, shipping_cost, total_price, address_title, address_province, address_city, address_detail, address_postal_code, address_lat, address_lng, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.ShippingCost,
			&i.TotalPrice,
			&i.AddressTitle,
			&i.AddressProvince,
			&i.AddressCity,
			&i.AddressDetail,
			&i.AddressPostalCode,
			&i.AddressLat,
			&i.AddressLng,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserAndStatus = `-- name: GetOrdersByUserAndStatus :many
SELECT id, user_id, status, shipping_cost, total_price, address_title, address_province, address_city, address_detail, address_postal_code, address_lat, address_lng, created_at, updated_at
FROM orders
WHERE user_id = $1
  AND status = $2
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type GetOrdersByUserAndStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetOrdersByUserAndStatus(ctx context.Context, arg GetOrdersByUserAndStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.ShippingCost,
			&i.TotalPrice,
			&i.AddressTitle,
			&i.AddressProvince,
			&i.AddressCity,
			&i.AddressDetail,
			&i.AddressPostalCode,
			&i.AddressLat,
			&i.AddressLng,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, status, shipping_cost, total_price, address_title, address_province, address_city, address_detail, address_postal_code, address_lat, address_lng, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ShippingCost,
		&i.TotalPrice,
		&i.AddressTitle,
		&i.AddressProvince,
		&i.AddressCity,
		&i.AddressDetail,
		&i.AddressPostalCode,
		&i.AddressLat,
		&i.AddressLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
