// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes
SET consumed_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (phone, code, purpose, full_name, password, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, phone, code, purpose, full_name, password, expires_at, consumed_at, attempts, created_at
`

type CreateOTPParams struct {
	Phone     string           `json:"phone"`
	Code      string           `json:"code"`
	Purpose   string           `json:"purpose"`
	FullName  pgtype.Text      `json:"full_name"`
	Password  pgtype.Text      `json:"password"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Phone,
		arg.Code,
		arg.Purpose,
		arg.FullName,
		arg.Password,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.Purpose,
		&i.FullName,
		&i.Password,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTPByPhonePurpose = `-- name: DeleteOTPByPhonePurpose :exec
DELETE FROM otp_codes
WHERE phone = $1 AND purpose = $2
`

type DeleteOTPByPhonePurposeParams struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

func (q *Queries) DeleteOTPByPhonePurpose(ctx context.Context, arg DeleteOTPByPhonePurposeParams) error {
	_, err := q.db.Exec(ctx, deleteOTPByPhonePurpose, arg.Phone, arg.Purpose)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, phone, code, purpose, full_name, password, expires_at, consumed_at, attempts, created_at FROM otp_codes
WHERE phone = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, arg.Phone, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.Purpose,
		&i.FullName,
		&i.Password,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2
WHERE id = $1
RETURNING id, full_name, phone, password, created_at, updated_at, is_admin
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}
