// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    amount,
    authority,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
`

type CreatePaymentParams struct {
	OrderID   uuid.UUID          `json:"order_id"`
	Amount    int64              `json:"amount"`
	Authority string             `json:"authority"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Amount,
		arg.Authority,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPaymentByAuthority = `-- name: GetPaymentByAuthority :one
SELECT id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
FROM payments
WHERE authority = $1
LIMIT 1
`

func (q *Queries) GetPaymentByAuthority(ctx context.Context, authority string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByAuthority, authority)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPaymentByAuthorityForUpdate = `-- name: GetPaymentByAuthorityForUpdate :one
SELECT id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
FROM payments
WHERE authority = $1
FOR UPDATE
`

func (q *Queries) GetPaymentByAuthorityForUpdate(ctx context.Context, authority string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByAuthorityForUpdate, authority)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
FROM payments
WHERE order_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markPaymentExpired = `-- name: MarkPaymentExpired :one
UPDATE payments
SET status = 'expired'
WHERE id = $1
  AND status = 'pending'
RETURNING id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
`

func (q *Queries) MarkPaymentExpired(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentExpired, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET
    status = 'failed',
    updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
`

func (q *Queries) MarkPaymentFailed(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET
    status = 'paid',
    ref_id = $2,
    card_pan = $3,
    card_hash = $4,
    fee_type = $5,
    fee = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, amount, authority, status, ref_id, card_pan, card_hash, fee_type, fee, created_at, updated_at, expires_at
`

type MarkPaymentPaidParams struct {
	ID       int64       `json:"id"`
	RefID    pgtype.Int8 `json:"ref_id"`
	CardPan  pgtype.Text `json:"card_pan"`
	CardHash pgtype.Text `json:"card_hash"`
	FeeType  pgtype.Text `json:"fee_type"`
	Fee      pgtype.Int8 `json:"fee"`
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid,
		arg.ID,
		arg.RefID,
		arg.CardPan,
		arg.CardHash,
		arg.FeeType,
		arg.Fee,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Authority,
		&i.Status,
		&i.RefID,
		&i.CardPan,
		&i.CardHash,
		&i.FeeType,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
