// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, discount, category_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price, discount, category_id, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Discount    pgtype.Numeric `json:"discount"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Discount,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Discount,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.discount,
    p.category_id,
    p.is_active,
    p.created_at,
    p.updated_at,

    COALESCE(
        (
            SELECT pi.url
            FROM product_images pi
            WHERE pi.product_id = p.id
              AND pi.is_primary = TRUE
            ORDER BY pi.created_at ASC
            LIMIT 1
        ),
        ''
    ) AS primary_image,

    (
        p.price - (p.price * p.discount / 100)
    )::bigint AS final_price,

    COALESCE(
        (
            SELECT SUM(oi.quantity)
            FROM order_items oi
            JOIN orders o
                ON o.id = oi.order_id
            WHERE oi.product_id = p.id
              AND o.status IN ('paid', 'shipped', 'delivered')
        ),
        0
    )::bigint AS sold_count,

    COALESCE(
        (
            SELECT ROUND(AVG(r.rating), 1)
            FROM reviews r
            WHERE r.product_id = p.id
              AND r.rating IS NOT NULL
        ),
        0
    )::numeric AS rating,

    (
        SELECT COUNT(*)
        FROM reviews r
        WHERE r.product_id = p.id
          AND r.rating IS NOT NULL
    )::bigint AS rating_count

FROM products p

WHERE p.is_active = TRUE

ORDER BY
    CASE
        WHEN $1::text = 'price_asc'
        THEN p.price - (p.price * p.discount / 100)
    END ASC NULLS LAST,

    CASE
        WHEN $1::text = 'price_desc'
        THEN p.price - (p.price * p.discount / 100)
    END DESC NULLS LAST,

    CASE
        WHEN $1::text = 'discount'
        THEN p.discount
    END DESC NULLS LAST,

    CASE
        WHEN $1::text = 'best_selling'
        THEN COALESCE(
            (
                SELECT SUM(oi.quantity)
                FROM order_items oi
                JOIN orders o
                    ON o.id = oi.order_id
                WHERE oi.product_id = p.id
                  AND o.status IN ('paid', 'shipped', 'delivered')
            ),
            0
        )
    END DESC NULLS LAST,

    p.created_at DESC,
    p.id DESC

LIMIT $3
OFFSET $2
`

type GetAllProductsParams struct {
	Sort   string `json:"sort"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

type GetAllProductsRow struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Price        pgtype.Numeric   `json:"price"`
	Discount     pgtype.Numeric   `json:"discount"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	PrimaryImage interface{}      `json:"primary_image"`
	FinalPrice   int64            `json:"final_price"`
	SoldCount    int64            `json:"sold_count"`
	Rating       pgtype.Numeric   `json:"rating"`
	RatingCount  int64            `json:"rating_count"`
}

func (q *Queries) GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error) {
	rows, err := q.db.Query(ctx, getAllProducts, arg.Sort, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllProductsRow{}
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Discount,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImage,
			&i.FinalPrice,
			&i.SoldCount,
			&i.Rating,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id, p.name, p.description, p.price, p.discount, p.category_id, p.is_active, p.created_at, p.updated_at,
    p.price - (p.price * p.discount / 100) AS final_price
FROM products p
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
	Discount    pgtype.Numeric   `json:"discount"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	FinalPrice  int32            `json:"final_price"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Discount,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalPrice,
	)
	return i, err
}

const getProductsByCategoryName = `-- name: GetProductsByCategoryName :many
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.discount,
    p.category_id,
    p.is_active,
    p.created_at,
    p.updated_at,
    COALESCE(
        (
            SELECT pi.url
            FROM product_images pi
            WHERE pi.product_id = p.id
              AND pi.is_primary = TRUE
            ORDER BY pi.created_at ASC
            LIMIT 1
        ),
        ''
    ) AS primary_image,
    (
        p.price - (p.price * p.discount / 100)
    )::bigint AS final_price,
    COALESCE(
        (
            SELECT SUM(oi.quantity)
            FROM order_items oi
            JOIN orders o ON o.id = oi.order_id
            WHERE oi.product_id = p.id
              AND o.status IN ('paid', 'shipped', 'delivered')
        ),
        0
    )::bigint AS sold_count
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = TRUE
  AND c.name = $1::text
ORDER BY
    CASE
        WHEN $2::text = 'price_asc'
        THEN p.price - (p.price * p.discount / 100)
    END ASC NULLS LAST,
    CASE
        WHEN $2::text = 'price_desc'
        THEN p.price - (p.price * p.discount / 100)
    END DESC NULLS LAST,
    CASE
        WHEN $2::text = 'discount'
        THEN p.discount
    END DESC NULLS LAST,
    CASE
        WHEN $2::text = 'best_selling'
        THEN COALESCE(
            (
                SELECT SUM(oi.quantity)
                FROM order_items oi
                JOIN orders o ON o.id = oi.order_id
                WHERE oi.product_id = p.id
                  AND o.status IN ('paid', 'shipped', 'delivered')
            ),
            0
        )
    END DESC NULLS LAST,
    p.created_at DESC,
    p.id DESC
LIMIT $4
OFFSET $3
`

type GetProductsByCategoryNameParams struct {
	CategoryName string `json:"category_name"`
	Sort         string `json:"sort"`
	Offset       int32  `json:"offset"`
	Limit        int32  `json:"limit"`
}

type GetProductsByCategoryNameRow struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Price        pgtype.Numeric   `json:"price"`
	Discount     pgtype.Numeric   `json:"discount"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	PrimaryImage interface{}      `json:"primary_image"`
	FinalPrice   int64            `json:"final_price"`
	SoldCount    int64            `json:"sold_count"`
}

func (q *Queries) GetProductsByCategoryName(ctx context.Context, arg GetProductsByCategoryNameParams) ([]GetProductsByCategoryNameRow, error) {
	rows, err := q.db.Query(ctx, getProductsByCategoryName,
		arg.CategoryName,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsByCategoryNameRow{}
	for rows.Next() {
		var i GetProductsByCategoryNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Discount,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImage,
			&i.FinalPrice,
			&i.SoldCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.discount,
    p.category_id,
    p.is_active,
    p.created_at,
    p.updated_at,

    COALESCE(
        (
            SELECT pi.url
            FROM product_images pi
            WHERE pi.product_id = p.id
              AND pi.is_primary = TRUE
            ORDER BY pi.created_at ASC
            LIMIT 1
        ),
        ''
    ) AS primary_image,

    (
        p.price - (p.price * p.discount / 100)
    )::bigint AS final_price,

    COALESCE(
        (
            SELECT SUM(oi.quantity)
            FROM order_items oi
            JOIN orders o
                ON o.id = oi.order_id
            WHERE oi.product_id = p.id
              AND o.status IN ('paid', 'shipped', 'delivered')
        ),
        0
    )::bigint AS sold_count

FROM products p

WHERE p.is_active = TRUE
  AND (
      p.name ILIKE '%' || $1 || '%'
      OR p.description ILIKE '%' || $1 || '%'
  )

ORDER BY
    CASE
        WHEN $2::text = 'price_asc'
        THEN p.price - (p.price * p.discount / 100)
    END ASC NULLS LAST,

    CASE
        WHEN $2::text = 'price_desc'
        THEN p.price - (p.price * p.discount / 100)
    END DESC NULLS LAST,

    CASE
        WHEN $2::text = 'discount'
        THEN p.discount
    END DESC NULLS LAST,

    CASE
        WHEN $2::text = 'best_selling'
        THEN COALESCE(
            (
                SELECT SUM(oi.quantity)
                FROM order_items oi
                JOIN orders o
                    ON o.id = oi.order_id
                WHERE oi.product_id = p.id
                  AND o.status IN ('paid', 'shipped', 'delivered')
            ),
            0
        )
    END DESC NULLS LAST,

    p.created_at DESC,
    p.id DESC

LIMIT $4
OFFSET $3
`

type SearchProductsParams struct {
	Query  pgtype.Text `json:"query"`
	Sort   string      `json:"sort"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

type SearchProductsRow struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Price        pgtype.Numeric   `json:"price"`
	Discount     pgtype.Numeric   `json:"discount"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	PrimaryImage interface{}      `json:"primary_image"`
	FinalPrice   int64            `json:"final_price"`
	SoldCount    int64            `json:"sold_count"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.Query,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Discount,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryImage,
			&i.FinalPrice,
			&i.SoldCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, description = $3, price = $4, discount = $5, category_id = $6, is_active = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, price, discount, category_id, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Discount    pgtype.Numeric `json:"discount"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Discount,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Discount,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
