// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) (CartItem, error)
	AddToWishlist(ctx context.Context, arg AddToWishlistParams) (Wishlist, error)
	ApproveReview(ctx context.Context, id int64) (ApproveReviewRow, error)
	BlockSession(ctx context.Context, id uuid.UUID) (Session, error)
	ClearCart(ctx context.Context, userID uuid.UUID) error
	ConsumeOTP(ctx context.Context, id uuid.UUID) error
	CreateBanner(ctx context.Context, arg CreateBannerParams) (Banner, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error)
	DecreaseVariantStock(ctx context.Context, arg DecreaseVariantStockParams) error
	DeleteBanner(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteOTPByPhonePurpose(ctx context.Context, arg DeleteOTPByPhonePurposeParams) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductImage(ctx context.Context, id uuid.UUID) error
	DeleteReview(ctx context.Context, arg DeleteReviewParams) error
	DeleteReviewByID(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error
	DeleteVariant(ctx context.Context, id uuid.UUID) error
	GetActiveBanners(ctx context.Context) ([]Banner, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAverageRating(ctx context.Context, productID uuid.UUID) (float64, error)
	GetCart(ctx context.Context, userID uuid.UUID) ([]GetCartRow, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpCode, error)
	GetLowStockProducts(ctx context.Context) ([]GetLowStockProductsRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error)
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error)
	GetOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error)
	GetOrdersByUserAndStatus(ctx context.Context, arg GetOrdersByUserAndStatusParams) ([]Order, error)
	GetPaidOrdersCount(ctx context.Context) (int64, error)
	GetPendingOrdersCount(ctx context.Context) (int64, error)
	// =========================================================
	// Admin Reviews
	// =========================================================
	GetPendingReviews(ctx context.Context) ([]GetPendingReviewsRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductImages(ctx context.Context, productID uuid.UUID) ([]ProductImage, error)
	GetProductsByCategoryName(ctx context.Context, arg GetProductsByCategoryNameParams) ([]GetProductsByCategoryNameRow, error)
	GetRecentOrders(ctx context.Context) ([]GetRecentOrdersRow, error)
	GetReviewsByProductID(ctx context.Context, productID uuid.UUID) ([]GetReviewsByProductIDRow, error)
	GetSalesLast7Days(ctx context.Context) ([]GetSalesLast7DaysRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetShippingCost(ctx context.Context) (int64, error)
	GetTodayOrdersCount(ctx context.Context) (int64, error)
	GetTodaySales(ctx context.Context) (interface{}, error)
	GetTopProducts(ctx context.Context) ([]GetTopProductsRow, error)
	GetUserAddress(ctx context.Context, arg GetUserAddressParams) (UserAddress, error)
	// internal/db/query/user_address.sql
	GetUserAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error)
	GetVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error)
	GetWishlistByUserID(ctx context.Context, userID uuid.UUID) ([]GetWishlistByUserIDRow, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error
	IsInWishlist(ctx context.Context, arg IsInWishlistParams) (bool, error)
	RejectReview(ctx context.Context, id int64) (RejectReviewRow, error)
	RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error
	RemoveFromWishlist(ctx context.Context, arg RemoveFromWishlistParams) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SearchUsers(ctx context.Context, query string) ([]SearchUsersRow, error)
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error
	UpdateBanner(ctx context.Context, arg UpdateBannerParams) (Banner, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateShippingCost(ctx context.Context, cost int64) (ShippingSetting, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error)
	UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (ProductVariant, error)
	// internal/db/query/review.sql
	// =========================================================
	// User Reviews
	// =========================================================
	UpsertReview(ctx context.Context, arg UpsertReviewParams) (UpsertReviewRow, error)
}

var _ Querier = (*Queries)(nil)
