// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE product_id = $1 AND user_id = $2
`

type DeleteReviewParams struct {
	ProductID uuid.UUID `json:"product_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) error {
	_, err := q.db.Exec(ctx, deleteReview, arg.ProductID, arg.UserID)
	return err
}

const getAverageRating = `-- name: GetAverageRating :one
SELECT COALESCE(AVG(rating::FLOAT), 0)::FLOAT AS average_rating
FROM reviews
WHERE product_id = $1
`

func (q *Queries) GetAverageRating(ctx context.Context, productID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getAverageRating, productID)
	var average_rating float64
	err := row.Scan(&average_rating)
	return average_rating, err
}

const getReviewsByProductID = `-- name: GetReviewsByProductID :many
SELECT
    r.id,
    r.product_id,
    r.user_id,
    u.full_name,
    r.rating,
    r.body,
    r.created_at,
    r.updated_at
FROM reviews r
JOIN users u ON u.id = r.user_id
WHERE r.product_id = $1
ORDER BY r.created_at DESC
`

type GetReviewsByProductIDRow struct {
	ID        int64              `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	UserID    uuid.UUID          `json:"user_id"`
	FullName  string             `json:"full_name"`
	Rating    pgtype.Int2        `json:"rating"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetReviewsByProductID(ctx context.Context, productID uuid.UUID) ([]GetReviewsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewsByProductIDRow{}
	for rows.Next() {
		var i GetReviewsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.FullName,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReview = `-- name: UpsertReview :one

INSERT INTO reviews (product_id, user_id, rating, body, updated_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
ON CONFLICT (product_id, user_id) DO UPDATE
SET
    rating     = EXCLUDED.rating,
    body       = EXCLUDED.body,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, product_id, user_id, rating, body, created_at, updated_at
`

type UpsertReviewParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Rating    pgtype.Int2 `json:"rating"`
	Body      pgtype.Text `json:"body"`
}

// internal/db/query/review.sql
func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, upsertReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Body,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
