// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping.sql

package db

import (
	"context"
)

const getShippingCost = `-- name: GetShippingCost :one
SELECT cost FROM shipping_settings WHERE id = 1
`

func (q *Queries) GetShippingCost(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getShippingCost)
	var cost int64
	err := row.Scan(&cost)
	return cost, err
}

const updateShippingCost = `-- name: UpdateShippingCost :one
UPDATE shipping_settings
SET cost = $1
WHERE id = 1
RETURNING id, cost
`

func (q *Queries) UpdateShippingCost(ctx context.Context, cost int64) (ShippingSetting, error) {
	row := q.db.QueryRow(ctx, updateShippingCost, cost)
	var i ShippingSetting
	err := row.Scan(&i.ID, &i.Cost)
	return i, err
}
