// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_adressess.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAddress = `-- name: CreateUserAddress :one
INSERT INTO user_addresses (user_id, title, province, city, address, postal_code, lat, lng, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, province, city, address, postal_code, lat, lng, is_default, created_at, updated_at
`

type CreateUserAddressParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Title      pgtype.Text    `json:"title"`
	Province   pgtype.Text    `json:"province"`
	City       pgtype.Text    `json:"city"`
	Address    pgtype.Text    `json:"address"`
	PostalCode pgtype.Text    `json:"postal_code"`
	Lat        pgtype.Numeric `json:"lat"`
	Lng        pgtype.Numeric `json:"lng"`
	IsDefault  bool           `json:"is_default"`
}

func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createUserAddress,
		arg.UserID,
		arg.Title,
		arg.Province,
		arg.City,
		arg.Address,
		arg.PostalCode,
		arg.Lat,
		arg.Lng,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Province,
		&i.City,
		&i.Address,
		&i.PostalCode,
		&i.Lat,
		&i.Lng,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserAddress = `-- name: DeleteUserAddress :exec
DELETE FROM user_addresses
WHERE id = $1 AND user_id = $2
`

type DeleteUserAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error {
	_, err := q.db.Exec(ctx, deleteUserAddress, arg.ID, arg.UserID)
	return err
}

const getUserAddress = `-- name: GetUserAddress :one
SELECT id, user_id, title, province, city, address, postal_code, lat, lng, is_default, created_at, updated_at
FROM user_addresses
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetUserAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserAddress(ctx context.Context, arg GetUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getUserAddress, arg.ID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Province,
		&i.City,
		&i.Address,
		&i.PostalCode,
		&i.Lat,
		&i.Lng,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many

SELECT id, user_id, title, province, city, address, postal_code, lat, lng, is_default, created_at, updated_at FROM user_addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

// internal/db/query/user_address.sql
func (q *Queries) GetUserAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAddress{}
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Province,
			&i.City,
			&i.Address,
			&i.PostalCode,
			&i.Lat,
			&i.Lng,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE user_addresses
SET
    is_default = (id = $1),
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $2
`

type SetDefaultAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, arg.ID, arg.UserID)
	return err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE user_addresses
SET
    title       = $1,
    province    = $2,
    city        = $3,
    address     = $4,
    postal_code = $5,
    lat         = $6,
    lng         = $7,
    is_default  = $8,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $9 AND user_id = $10
RETURNING id, user_id, title, province, city, address, postal_code, lat, lng, is_default, created_at, updated_at
`

type UpdateUserAddressParams struct {
	Title      pgtype.Text    `json:"title"`
	Province   pgtype.Text    `json:"province"`
	City       pgtype.Text    `json:"city"`
	Address    pgtype.Text    `json:"address"`
	PostalCode pgtype.Text    `json:"postal_code"`
	Lat        pgtype.Numeric `json:"lat"`
	Lng        pgtype.Numeric `json:"lng"`
	IsDefault  bool           `json:"is_default"`
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, updateUserAddress,
		arg.Title,
		arg.Province,
		arg.City,
		arg.Address,
		arg.PostalCode,
		arg.Lat,
		arg.Lng,
		arg.IsDefault,
		arg.ID,
		arg.UserID,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Province,
		&i.City,
		&i.Address,
		&i.PostalCode,
		&i.Lat,
		&i.Lng,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
