// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variant.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (product_id, label, color, stock)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, label, color, stock, created_at, updated_at
`

type CreateVariantParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	Label     string      `json:"label"`
	Color     pgtype.Text `json:"color"`
	Stock     int32       `json:"stock"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.Label,
		arg.Color,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Color,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decreaseVariantStock = `-- name: DecreaseVariantStock :one

UPDATE product_variants
SET
    stock = stock - $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND stock >= $2
RETURNING stock
`

type DecreaseVariantStockParams struct {
	ID    uuid.UUID `json:"id"`
	Stock int32     `json:"stock"`
}

func (q *Queries) DecreaseVariantStock(ctx context.Context, arg DecreaseVariantStockParams) (int32, error) {
	row := q.db.QueryRow(ctx, decreaseVariantStock, arg.ID, arg.Stock)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM product_variants
WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, id)
	return err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, product_id, label, color, stock, created_at, updated_at FROM product_variants
WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Color,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantsByProductID = `-- name: GetVariantsByProductID :many
SELECT id, product_id, label, color, stock, created_at, updated_at FROM product_variants
WHERE product_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, getVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Label,
			&i.Color,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderAsPaid = `-- name: MarkOrderAsPaid :one
UPDATE orders
SET
    status = 'paid',
    updated_at = NOW()
WHERE id = $1
  AND status <> 'paid'
RETURNING id, user_id, status, shipping_cost, total_price, address_title, address_province, address_city, address_detail, address_postal_code, address_lat, address_lng, created_at, updated_at, discount_code, discount_amount
`

func (q *Queries) MarkOrderAsPaid(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderAsPaid, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ShippingCost,
		&i.TotalPrice,
		&i.AddressTitle,
		&i.AddressProvince,
		&i.AddressCity,
		&i.AddressDetail,
		&i.AddressPostalCode,
		&i.AddressLat,
		&i.AddressLng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountCode,
		&i.DiscountAmount,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET
    label = $2,
    color = $3,
    stock = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, label, color, stock, created_at, updated_at
`

type UpdateVariantParams struct {
	ID    uuid.UUID   `json:"id"`
	Label string      `json:"label"`
	Color pgtype.Text `json:"color"`
	Stock int32       `json:"stock"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.Label,
		arg.Color,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Color,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariantStock = `-- name: UpdateVariantStock :one
UPDATE product_variants
SET stock = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, label, color, stock, created_at, updated_at
`

type UpdateVariantStockParams struct {
	ID    uuid.UUID `json:"id"`
	Stock int32     `json:"stock"`
}

func (q *Queries) UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariantStock, arg.ID, arg.Stock)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Color,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
