// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wishlist.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToWishlist = `-- name: AddToWishlist :one
INSERT INTO wishlists (user_id, product_id)
VALUES ($1, $2)
ON CONFLICT (user_id, product_id) DO NOTHING
RETURNING id, user_id, product_id, created_at
`

type AddToWishlistParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) AddToWishlist(ctx context.Context, arg AddToWishlistParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, addToWishlist, arg.UserID, arg.ProductID)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const getWishlistByUserID = `-- name: GetWishlistByUserID :many

SELECT
    w.id,
    w.created_at,
    p.id AS id,
    p.name AS name,
    p.price AS price,
    p.discount AS discount,
    p.is_active AS is_active,
    c.name AS category_name,
    (
        SELECT url
        FROM product_images
        WHERE product_id = p.id
          AND is_primary = true
        LIMIT 1
    ) AS primary_image,
    p.price - (p.price * p.discount / 100) AS final_price
FROM wishlists w
JOIN products p
    ON p.id = w.product_id
LEFT JOIN categories c
    ON c.id = p.category_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type GetWishlistByUserIDRow struct {
	ID           uuid.UUID          `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ID_2         uuid.UUID          `json:"id_2"`
	Name         string             `json:"name"`
	Price        pgtype.Numeric     `json:"price"`
	Discount     pgtype.Numeric     `json:"discount"`
	IsActive     bool               `json:"is_active"`
	CategoryName pgtype.Text        `json:"category_name"`
	PrimaryImage string             `json:"primary_image"`
	FinalPrice   int32              `json:"final_price"`
}

func (q *Queries) GetWishlistByUserID(ctx context.Context, userID uuid.UUID) ([]GetWishlistByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getWishlistByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWishlistByUserIDRow{}
	for rows.Next() {
		var i GetWishlistByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ID_2,
			&i.Name,
			&i.Price,
			&i.Discount,
			&i.IsActive,
			&i.CategoryName,
			&i.PrimaryImage,
			&i.FinalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isInWishlist = `-- name: IsInWishlist :one
SELECT EXISTS (
    SELECT 1 FROM wishlists
    WHERE user_id = $1 AND product_id = $2
) AS exists
`

type IsInWishlistParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) IsInWishlist(ctx context.Context, arg IsInWishlistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInWishlist, arg.UserID, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeFromWishlist = `-- name: RemoveFromWishlist :exec
DELETE FROM wishlists
WHERE user_id = $1 AND product_id = $2
`

type RemoveFromWishlistParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) RemoveFromWishlist(ctx context.Context, arg RemoveFromWishlistParams) error {
	_, err := q.db.Exec(ctx, removeFromWishlist, arg.UserID, arg.ProductID)
	return err
}
